name: Benchmark

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
  # post on the pull-request page
  pull-requests: write

jobs:
  benchmark:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run benchmark
        run: bash ./generate_data.sh "${{ runner.arch }}-${{ runner.os }}"
      - name: Compare result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "customBiggerIsBetter"
          output-file-path: ./random_data.json
          alert-threshold: "120%"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: false
          comment-on-alert: false # see https://github.com/benchmark-action/github-action-benchmark/issues/158
          summary-always: false # see https://github.com/benchmark-action/github-action-benchmark/issues/158
          comment-always: false # see https://github.com/benchmark-action/github-action-benchmark/issues/158
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          save-data-file: ${{ github.ref == 'refs/heads/main' }}
